=== kasko/kasko-app-example-external/schema/product.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "index": {
      "type": "string"
    },
    "integrations": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "version_id": {
            "type": "string"
          },
          "index": {
            "type": "string"
          },
          "css": {
            "type": "string"
          }
        },
        "required": [
          "version_id",
          "index"
        ]
      }
    }
  },
  "required": [
    "id",
    "index",
    "integrations"
  ]
}

=== kasko/kasko-app-example-external/product.json
{
  "$schema": "./schema/product.schema.json",
  "name": "Test",
  "id": "pr_111",
  "index": "./src/product/index.js",
  "integrations": {
    "in_222": {
      "name": "Distributor 1",
      "version_id": "ins_333",
      "index": "./src/integrations/test1/index.js",
      "css": "./src/integrations/test1/style.css"
    }
  }
}
